# Greedy (demo)

In [13]:
import math
import time
import os
import csv
import re
from datetime import datetime
from pathlib import Path
import numpy as np
import pandas as pd

In [14]:
# convert txt to csv

# input test demo file and convert to csv
input_file = "HMM_Algeciras.txt"
output_file = "HMM_Algeciras.csv"

pattern = r"\[(\d+),(\d+)\], \{(\d+)\}, (.*)"

with open(input_file, "r") as infile, open(output_file, "w", newline="") as outfile:
    writer = csv.writer(outfile)
    writer.writerow(["row", "column", "weight", "description"])

    for line in infile:
        line = line.strip()
        match = re.match(pattern, line)
        if match:
            row, col, weight, desc = match.groups()
            writer.writerow([row, col, weight, desc])

print(f"Done: {output_file}")


Done: HMM_Algeciras.csv


1. Define the representation and initial state, and import and define dataset:

    - Convert given dataset to 2D numpy array
    - Dataset generate by us in additional to given test set
    
*Note that crane located at [0, 8] (by slides, just above [1, 8])*

In [15]:
# This is for given test set only because row 1 start from bottom- need to flip it during computing.
# Store mainfest: NAN as -1, 0 as empty, >0 as occupied, number are weight of the container
def create_grid(path):
    df = pd.read_csv(path)
    nrows = int(df["row"].max()) + 1
    ncols = int(df["column"].max())
    grid = np.zeros((nrows, ncols), dtype=int)

    for _, rec in df.iterrows():
        r = nrows - int(rec["row"])
        c = int(rec["column"]) - 1
        desc = str(rec["description"]).strip().upper()

        if desc == "NAN":
            grid[r, c] = -1
        elif desc == "UNUSED":
            grid[r, c] = 0
        else:
            grid[r, c] = int(rec["weight"])
    return grid

test_demo = create_grid(output_file)
test_demo

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ -1,   0,   0,   0,   0,   0,   0, 123,   0, 300,   0,  -1]])

At this points, all dataset are store in 2D numpy array format, 9 by 12

2. Define goal state

In [16]:
def left_weight(grid):
    return int(np.clip(grid[1:9, 0:6], 0, None).sum())

def right_weight(grid):
    return int(np.clip(grid[1:9, 6:12], 0, None).sum())

def which_side_is_heavier(grid):
    left = left_weight(grid)
    right = right_weight(grid)
    return (0, 6) if left > right else (6, 12)

def goal_test(grid, tol=0.10):
    total = left_weight(grid) + right_weight(grid)
    return True if total == 0 else abs(left_weight(grid) - right_weight(grid)) <= tol * total

# determine if the grid is balanceable
def is_balanceable(grid):
    container = []

    # loop all grid(each col and row), add each non zero value to container list
    for row in grid:
        for col in row:
            if col != 0 and col != -1:
                container.append(col)

    # check if the container list is balanceable
    total = sum(container)
    threshold = total * 0.1
    n = len(container)

    # use brute force to check all combination since max 16 containers
    for mask in range(1, (1 << n)):
        sum1 = 0
        for i in range(n):
            if mask & (1 << i):
                sum1 += container[i]
        
        sum2 = total - sum1
        if abs(sum1 - sum2) <= threshold:
            return True
    
    return False

# goal_test(grid4)

In [17]:
# def get_set_data(data):
#     left = left_weight(data)
#     right = right_weight(data)
#     goal = goal_test(data)
#     total = left + right
#     needed = math.ceil((abs(left-right) - 0.1*total) / 2)

#     print("Left: ", left, "\nRight: ", right)
#     print("Total: ", total)
#     print("Diff: ", abs(left-right))
#     print("Goal: ", goal)
#     print("Target: ", 0.1*total) # weight diff small or equal to this number
#     print("Needed: ", needed)

# get_set_data(grid7)

3. Define the operators (What to move)

In [18]:
def determine_container_to_move(grid):
    # compute which side is heavier
    left_sum = left_weight(grid)
    right_sum = right_weight(grid)

    # already perfectly balanced → nothing to move
    if left_sum == right_sum:
        return [], 0

    heavy_is_left = left_sum > right_sum
    low, high = (0, 6) if heavy_is_left else (6, 12)

    diff = abs(left_sum - right_sum)

    # candidate containers only on the heavier side
    candidates = [((row, col), int(grid[row, col]))
                  for row in range(grid.shape[0])
                  for col in range(low, high)
                  if int(grid[row, col]) > 0]

    n = len(candidates)
    weights = [w for _, w in candidates]

    best_mask = None
    best_diff = None

    # brute force all non-empty subsets of candidates
    for mask in range(1, 1 << n):
        moved_weight = 0
        for i in range(n):
            if mask & (1 << i):
                moved_weight += weights[i]

        # new difference after moving this subset to the other side
        new_diff = abs(diff - 2 * moved_weight)

        # choose subset that minimizes new_diff
        # tie-break: fewer containers moved
        if (best_diff is None or
            new_diff < best_diff or
            (new_diff == best_diff and
             bin(mask).count("1") < bin(best_mask).count("1"))):
            best_diff = new_diff
            best_mask = mask

    chosen = []
    for i in range(n):
        if best_mask & (1 << i):
            chosen.append(candidates[i])

    # 'needed' is no longer used by the move function, so return a dummy value
    return chosen, 0


# candidates, needed = determine_container_to_move(grid4)
# candidates, needed


After determine which container need to move, now it's time to move them (greedy move):

4. Search algorithm (Actual Operation)

    - If there are a container above it, move it into nearest column on the same side.
    - Slide horizontally to the right: grid to the right might be blocked, move up until right cell is empty; then move right; repeat if same silution happen. 
    - Drop down. Once on the target side, drop it down. To save steps, can drop on columns that nearest the border. 

In [19]:
# check container above it
def is_container_above(grid, row, col):
    return row > 0 and grid[row - 1, col] > 0

# handle vertical move in a column(where to drop in this column)
def find_drop_in_column(grid, col):
    last = grid.shape[0] - 1
    if grid[last, col] == 0:
        return (last, col)
    for row in range(last - 1, 0, -1):
        if grid[row, col] == 0 and grid[row + 1, col] > 0:
            return (row, col)
    return None

# handle horizontal move in a column(which column should drop to)
def nearest_empty_column(grid, src_col, target_cols):
    available = []
    for c in target_cols:
        drop = find_drop_in_column(grid, c)
        if drop is not None:
            available.append((abs(c - src_col), drop))

    if not available:
        return None

    _, best_drop = min(available, key=lambda x: x[0])
    return best_drop

# find_drop_in_column(grid4, 0)
# nearest_empty_column(grid4, 0, range(11, 5, -1))


In [20]:
# helper function: find destination
def find_destination(grid, target_cols):
    last_row = grid.shape[0] - 1

    # a. last row first
    for col in target_cols:
        if grid[last_row, col] == 0:
            return (last_row, col)

    # b. if no bottom slots, stack upward
    for row in range(last_row - 1, 0, -1):
        for col in target_cols:
            if grid[row, col] == 0 and grid[row + 1, col] > 0:
                return (row, col)

    raise ValueError("No destination found")

# main function: move container to another side
def move_container_another_side(grid, container_to_move, log_print=print):

    move_count = 0

    # check which side is heavier
    heavier_side = which_side_is_heavier(grid)
    target_cols = range(11, 5, -1) if heavier_side == (0, 6) else range(0, 6)

    # crane location
    PARK = (0, 8)
    crane_row, crane_col = PARK

    # track steps
    per_container_steps = []
    total_steps = 0

    # start moving
    for (src_row, src_col), _  in container_to_move:

        # a. clear blockers on SAME side
        same_side = range(0, 6) if src_col < 6 else range(6, 12)
        while is_container_above(grid, src_row, src_col):
            blocker_row = src_row - 1

            # choose nearest same-side column with a legal drop spot
            stash_cols = [c for c in same_side if c != src_col]
            drop = nearest_empty_column(grid, src_col, stash_cols)
            if drop is None:
                raise ValueError("No place to stash a blocker on this side")

            drb, dcb = drop

            leg1 = abs(crane_row - blocker_row) + abs(crane_col - src_col)
            leg2 = abs(drb - blocker_row) + abs(dcb - src_col)

            grid[drb, dcb] = grid[blocker_row, src_col]
            grid[blocker_row, src_col] = 0

            crane_row, crane_col = drb, dcb
            step_block = leg1 + leg2
            total_steps += step_block
            per_container_steps.append(((blocker_row, src_col), (drb, dcb), step_block))
        
        destination = find_destination(grid, target_cols)
        
        dr, dc = destination
        # move 1: crane -> container(diatance from current crane pos to next containers pos)
        move1 = abs(crane_row - src_row) + abs(crane_col - src_col)
        # move 2: container -> destination(distance to carry container from it source to target destination)
        move2 = abs(dr - src_row) + abs(dc - src_col)

        # perform move
        grid[dr, dc] = grid[src_row, src_col]
        grid[src_row, src_col] = 0

        crane_row, crane_col = dr, dc  # update crane pos

        # update steps
        steps = move1 + move2
        per_container_steps.append(((src_row, src_col), (dr, dc), steps))
        total_steps += steps

        move_count += 1
        log_print(f"Move {move_count}: [{src_row}, {src_col}] -> [{dr}, {dc}], Steps(minutes): {steps}")

    # final move: crane -> park
    total_steps += abs(crane_row - PARK[0]) + abs(crane_col - PARK[1])


    return grid, per_container_steps, total_steps
        
# test
# grid, per_container_steps, total_steps = move_container_another_side(grid4, candidates)
# print("\nGrid: \n", grid)
# print("\nMoves: \n", per_container_steps)
# print(f"\nTotal steps: {total_steps}")

In [21]:
# ask user to make a comment and print in log file
comment = input("Any comments about this run? (press Enter to skip): ")
comment = comment.strip() if comment.strip() else "N/A"
comment

'N/A'

In [22]:
def main(grid, grid_name="grid", comment="N/A"):
    
    # generate log: {txt prefix}MM_DD_YYYY_HHMM_gridN.txt
    now = datetime.now()
    timestamp = now.strftime("%m_%d_%Y_%H%M")
    # output log name should be same with txt prefix
    prefix = os.path.splitext(input_file)[0]
    log_filename = f"{prefix}{timestamp}.txt"
    
    # write log file in the same folder
    log_file = log_filename
    
    with open(log_file, "w") as f:
        def log_print(*args, **kwargs):
            # Add timestamp to each log entry
            timestamp_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            msg = " ".join(str(arg) for arg in args)
            log_entry = f"[{timestamp_str}] {msg}"
            print(*args, **kwargs)
            f.write(log_entry + "\n")
            f.flush()

        log_print("Program starts. ")
        container_count = np.sum((grid > 0))
        log_print(f"File open, this is {grid_name}. There are total of {container_count} containers on the ship.")

        # 1. check if already legally balanced (<= 10%)
        if goal_test(grid):
            log_print("This mainfest is already balanced (<= 10%), no action needed.")
            total_steps = 0
            log_print(f"A comment was written to the log : {comment}")
            log_print(f"Program ends. Computation time: {total_steps} minutes")
            return None, [], 0

        # 2. otherwise: try to improve balance (even if 10% is impossible)
        current_diff = abs(left_weight(grid) - right_weight(grid))
        total = left_weight(grid) + right_weight(grid)
        log_print(
            f"This manifest is not currently balanced. "
            f"Left = {left_weight(grid)}, Right = {right_weight(grid)}, "
            f"Diff = {current_diff}, 10% target = {0.1 * total:.2f}"
        )
        log_print("Attempting to reduce the left-right difference as much as possible.")

        # 3. determine which container(s) to move
        candidates, needed = determine_container_to_move(grid)

        # 4. move container(s) to the other side
        grid, per_container_steps, total_steps = move_container_another_side(grid, candidates, log_print)
        log_print(f"Finished a cycle. Total steps: {total_steps}")
        log_print(f"Balanced Grid (locally minimal difference): \n{grid}")
        
        # End timing and log (1 move = 1 minute)
        log_print("File was written to destop.")
        log_print(f"A comment was written to the log : {comment}")
        log_print(f"Program ends. Computation time: {total_steps} minutes")

    return grid, per_container_steps, total_steps


In [23]:
# Process test_demo and generate log file
print("Processing test_demo...")
result = main(test_demo, grid_name="test_demo", comment=comment)
print(f"Completed. Log file saved in current folder.")

Processing test_demo...
Program starts. 
File open, this is test_demo. There are total of 2 containers on the ship.
This manifest is not currently balanced. Left = 0, Right = 423, Diff = 423, 10% target = 42.30
Attempting to reduce the left-right difference as much as possible.
Move 1: [8, 7] -> [8, 1], Steps(minutes): 15
Finished a cycle. Total steps: 30
Balanced Grid (locally minimal difference): 
[[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]
 [ -1 123   0   0   0   0   0   0   0 300   0  -1]]
File was written to destop.
A comment was written to the log : N/A
Program ends. Computation time: 30 minutes
Completed. Log file saved i